sources:
  # Спецтехника и коммерческий транспорт — общий профильный портал
  - id: st-kt-main
    enabled: true
    kind: rss
    title: "Спецтехника и коммерческий транспорт — st-kt.ru"
    url: "https://st-kt.ru/rss"
    tags:
      - спецтехника
      - прицепы
      - полуприцепы
      - грузовики

  # Грузовой.ру — новости по рынку грузовых автомобилей
  - id: gruzovoy-ru
    enabled: true
    kind: rss
    title: "Грузовой.ру — рынок грузовиков"
    url: "https://gruzovoy.ru/rss"
    tags:
      - грузовики
      - рынок
      - статистика

  # Металлоснабжение и сбыт — тематическая рубрика "Рынок грузовиков"
  - id: metalinfo-trucks
    enabled: true
    kind: rss
    title: "Рынок грузовиков — Металлоснабжение и сбыт"
    url: "https://rss.metalinfo.ru/ru/news/s7170.rss"
    tags:
      - рынок
      - грузовики
      - аналитика

  # Ведомости — коммерческий транспорт (деловая пресса)
  - id: vedomosti-commercial-vehicles
    enabled: true
    kind: rss
    title: "Ведомости — коммерческие автомобили"
    url: "https://www.vedomosti.ru/rss/rubric/auto/commercial_vehicles"
    tags:
      - коммерческий транспорт
      - грузовики
      - бизнес

  # Truckmix — отраслевые новости по спецтехнике и грузовому транспорту
  - id: truckmix-industry
    enabled: true
    kind: rss
    title: "Truckmix — отраслевые новости спецтехники"
    url: "https://truckmix.ru/publication/rss?type=1"
    tags:
      - спецтехника
      - грузовики
      - прицепы

# Конфигурация каналов YouTube — пока не используется агрегатором,
# но пригодится дальше для видео-раздела
youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "Прицепы и полуприцепы SATpricep"
    videos:
      - "jQQzPo6YWPg"
      - "AwMnAEEOfoM"
      - "_6JdduOi4CE"
      - "1ZKbQu2NQ4s"
      - "1ZKbQu2NQ4s"
      - "JArHntGs9iM"

  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "Прицепы TRAILUX"
    videos:
      - "Qwerty123456"
      - "Asdfgh987654"
      - "D23J8D4u6wM"
      - "BfiLaIvHHVM"
      - "jd7f2w7T318"
      - "lltCXceqVVE"
      - "tcBJMYV16cs"

