# Основные новостные источники
sources:
  - id: truckmix-industry
    enabled: true
    kind: rss
    title: "TRUCKMIX — новости спецтехники и грузового транспорта"
    url: "https://truckmix.ru/publication/rss?type=1"
    tags:
      - спецтехника
      - грузовики
      - прицепы

  - id: stkt-magazine
    enabled: true
    kind: rss
    title: "Журнал «СпецТехника и Коммерческий Транспорт»"
    url: "https://st-kt.ru/rss"
    tags:
      - спецтехника
      - коммерческий транспорт
      - полуприцепы

  - id: comautotrans-news
    enabled: true
    kind: rss
    title: "ComAutoTrans — новости выставки коммерческого транспорта"
    url: "https://comautotrans.moscow/rss-feed-223104201511.xml"
    tags:
      - выставки
      - коммерческий транспорт
      - прицепы

  - id: sbsgroup-telematics
    enabled: true
    kind: rss
    title: "SBS Group — мониторинг и цифровизация транспорта"
    url: "https://sbsgroup-rus.ru/rss-feed-704478702641.xml"
    tags:
      - телематика
      - мониторинг
      - коммерческий транспорт

# Конфигурация каналов YouTube — пока не используется агрегатором,
# но пригодится дальше для видео-раздела
youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "Прицепы и полуприцепы SATpricep"
    videos:
      - "jQQzPo6YWPg"
      - "AwMnAEEOfoM"
      - "_6JdduOi4CE"
      - "1ZKbQu2NQ4s"
      - "1ZKbQu2NQ4s"
      - "JArHntGs9iM"

  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "Прицепы TRAILUX"
    videos:
      - "Qwerty123456"
      - "Asdfgh987654"
      - "D23J8D4u6wM"
      - "BfiLaIvHHVM"
      - "jd7f2w7T318"
      - "lltCXceqVVE"
      - "tcBJMYV16cs"

