# Источники новостей для агрегатора.
# Весь файл — это список элементов (list), без корневого ключа вроде `sources:`.

- id: gruzovoy-ru
  enabled: true
  kind: rss
  title: "Грузовой Ру — грузовые автомобили, прицепы, коммерческий транспорт"
  url: "https://gruzovoy.ru/rss"
  tags:
    - отрасль
    - грузовики
    - прицепы
    - коммерческий транспорт

- id: st-kt
  enabled: true
  kind: rss
  title: "Журнал «СпецТехника и Коммерческий Транспорт»"
  url: "https://st-kt.ru/rss"
  tags:
    - отрасль
    - спецтехника
    - грузовики
    - прицепы
    - рынок

- id: motor-ru
  enabled: true
  kind: rss
  title: "Motor.ru — автомобильные новости"
  url: "https://motor.ru/exports/rss"
