
- id: trailer-press
  enabled: true          # включить источник
  kind: rss              # тип источника (rss / atom / api — в проекте используется rss)
  title: "Новости прицепов и полуприцепов — Trailer-Press"
  url: "https://example.com/rss/trailers.xml"
  tags:
    - отрасль
    - прицепы

- id: truck-market
  enabled: true
  kind: rss
  title: "Рынок грузовиков и полуприцепов"
  url: "https://example.com/rss/truck-market.xml"
  tags:
    - рынок
    - аналитика

# при необходимости позже добавишь сюда ещё источники по тому же шаблону:
# - id: ...
#   enabled: true
#   kind: rss
#   title: "Человекочитаемое имя"
#   url: "https://адрес/rss"
#   tags:
#     - тег1
#     - тег2






youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "ы"
  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "i"
vk:
  - domain: "specavto_official"  # https://vk.com/specavto_official
    name: "СпецАвто"
