sources:
  # ===== Твои русскоязычные источники (оставил только прицепную/полуприцепную тематику) =====
  - id: truckmix-industry
    enabled: true
    kind: rss
    title: "TRUCKMIX — новости спецтехники и грузового транспорта"
    url: "https://truckmix.ru/publication/rss?type=1"
    tags:
      - спецтехника
      - грузовики
      - прицепы
      - полуприцепы

  - id: gruzovoy-main
    enabled: true
    kind: rss
    title: "Грузовой Ру — грузовые автомобили, прицепы и полуприцепы"
    url: "https://gruzovoy.ru/rss"
    tags:
      - грузовики
      - прицепы
      - полуприцепы
      - рынок

  - id: vedomosti-commercial
    enabled: true
    kind: rss
    title: "Коммерческие автомобили — Ведомости"
    url: "https://www.vedomosti.ru/rss/rubric/auto/commercial_vehicles"
    tags:
      - коммерческий транспорт
      - экономика
      - грузовики
      - прицепы
      - полуприцепы

  - id: comautotrans-news
    enabled: true
    kind: rss
    title: "ComAutoTrans — новости выставки коммерческого транспорта"
    url: "https://comautotrans.moscow/rss-feed-223104201511.xml"
    tags:
      - выставки
      - коммерческий транспорт
      - прицепы
      - полуприцепы

  # ===== 5 иностранных источников (для теста перевода title/summary) =====
  - id: globaltrailer-main
    enabled: true
    kind: rss
    title: "Global Trailer — новости индустрии полуприцепов"
    url: "https://www.globaltrailermag.com/feed/"
    tags:
      - полуприцепы
      - прицепы
      - иностранные
      - производители

  - id: krone-news
    enabled: true
    kind: rss
    title: "KRONE Trailer — новости производителя"
    url: "https://www.krone-trailer.com/en/news/rss-feed"
    tags:
      - полуприцепы
      - прицепы
      - иностранные
      - производители
      - krone

  - id: koegel-pressebox
    enabled: true
    kind: rss
    title: "Kögel — пресс-релизы (PresseBox)"
    url: "https://www.pressebox.de/rss/pressemitteilungen/newsroom/koegel-trailer-gmbh-cokg"
    tags:
      - полуприцепы
      - прицепы
      - иностранные
      - производители
      - пресс-релизы
      - koegel

  - id: wielton-stockwatch
    enabled: true
    kind: rss
    title: "Wielton — официальные сообщения (StockWatch)"
    url: "https://www.stockwatch.pl/komunikaty-spolek/rss.aspx?t=WIELTON"
    tags:
      - полуприцепы
      - прицепы
      - иностранные
      - производители
      - официально
      - wielton

  - id: trailertechnician-main
    enabled: true
    kind: rss
    title: "Trailer Technician — новости полуприцепной индустрии"
    url: "https://trailertechnician.com/feed/"
    tags:
      - полуприцепы
      - прицепы
      - иностранные
      - компоненты
      - сервис


youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "Прицепы и полуприцепы SATpricep"
    videos:
      - "jQQzPo6YWPg"
      - "AwMnAEEOfoM"
      - "_6JdduOi4CE"
      - "1ZKbQu2NQ4s"
      - "JArHntGs9iM"

  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "Прицепы TRAILUX"
    videos:
      - "Qwerty123456"
      - "Asdfgh987654"
      - "D23J8D4u6wM"
      - "BfiLaIvHHVM"
      - "jd7f2w7T318"
      - "lltCXceqVVE"
      - "tcBJMYV16cs"

vk:
  - domain: "specavto_official"  # https://vk.com/specavto_official
    name: "СпецАвто"
