sources:
  - id: kolesa
    enabled: true
    kind: rss
    title: "Автоновости — Kolesa.ru"
    url: "https://www.kolesa.ru/export/rss.xml"
    tags:
      - легковые
      - рынок
      - общие-авто

  - id: gazeta-autonews
    enabled: true
    kind: rss
    title: "Автоновости — Газета.Ru"
    url: "https://www.gazeta.ru/export/rss/autonews.xml"
    tags:
      - легковые
      - рынок
      - общие-авто

  - id: gruzovoy
    enabled: true
    kind: rss
    title: "Грузовые автомобили и прицепы — Грузовой.ру"
    url: "https://gruzovoy.ru/rss"
    tags:
      - грузовики
      - прицепы
      - коммерческий-транспорт

  - id: truckmix
    enabled: true
    kind: rss
    title: "Спецтехника и грузовой транспорт — TRUCKMIX.ru"
    url: "https://truckmix.ru/publication/rss?type=1"
    tags:
      - спецтехника
      - грузовики
      - коммерческий-транспорт

  - id: rg-autopark
    enabled: true
    kind: rss
    title: "Автопарк — Российская газета"
    url: "https://rg.ru/xml/index.xml"
    tags:
      - легковые
      - рынок
      - общие-авто

# Конфигурация каналов YouTube — пока не используется агрегатором,
# но пригодится дальше для видео-раздела
youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "Прицепы и полуприцепы SATpricep"
    videos:
      - "jQQzPo6YWPg"
      - "AwMnAEEOfoM"
      - "_6JdduOi4CE"
      - "1ZKbQu2NQ4s"
      - "1ZKbQu2NQ4s"
      - "JArHntGs9iM"

  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "Прицепы TRAILUX"
    videos:
      - "Qwerty123456"
      - "Asdfgh987654"
      - "D23J8D4u6wM"
      - "BfiLaIvHHVM"
      - "jd7f2w7T318"
      - "lltCXceqVVE"
      - "tcBJMYV16cs"

