# Примеры источников (дополните своими)
# rss:
#   - name: "Autosport"
#     url: "https://autosport.com.ru/rss/all.xml"   # RSS-лента
#     homepage: "https://autosport.com.ru/"          # ссылка на первоисточник
#     full_content: true 

#   - name: "LogNews"
#     url: "https://lognews.ru/rss"
#     homepage: "https://lognews.ru"
#     full_content: true 

#   - name: "Пресс-релизы производителя А"
#     url: "https://www.faymonville.com/news-ru/rss"
#     homepage: "https://www.faymonville.com/ru/news/"
#     type: "manufacturer"
#     full_content: true 

# Список RSS-источников. Формат: массив словарей с name и url.
sources:
  - name: Drom — Автоновости
    url: https://www.drom.ru/cached_files/xml/news.rss
    full_content: true 

  - name: Transport Topics
    url: https://www.ttnews.com/categories/trailers-0
    full_content: true 

  - name: Ведомости — Коммерческие авто
    url: https://www.vedomosti.ru/rss/rubric/auto/commercial_vehicles
    full_content: true 

  - name: Ведомости — Транспорт
    url: https://www.vedomosti.ru/rss/rubric/business/transport
    full_content: true 

  - name: LOGIRUS — Новости логистики
    url: https://logirus.ru/news/10/rss/
    full_content: true 

  - name: grozovoy.ru
    url: https://gruzovoy.ru/rss
    full_content: true 
  - name: Za-rulem
    url: https://www.zr.ru/rss-news/
    full_content: true 


youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "ы"
  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "i"
vk:
  - domain: "specavto_official"  # https://vk.com/specavto_official
    name: "СпецАвто"
