# Основные новостные источники (RSS)
sources:
  - id: st-kt
    enabled: true
    kind: rss
    title: "СпецТехника и Коммерческий Транспорт"
    url: "https://st-kt.ru/rss"
    tags:
      - спецтехника
      - прицепы
      - грузовики

  - id: gruzovoy-ru
    enabled: true
    kind: rss
    title: "Грузовой Ру — грузовые автомобили, прицепы и полуприцепы"
    url: "https://gruzovoy.ru/rss"
    tags:
      - грузовики
      - прицепы
      - рынок

  - id: vedomosti-commercial
    enabled: true
    kind: rss
    title: "Ведомости — коммерческий транспорт"
    url: "https://www.vedomosti.ru/rss/rubric/auto/commercial_vehicles"
    tags:
      - рынок
      - аналитика
      - коммерческий транспорт

  - id: metalinfo-trucks
    enabled: true
    kind: rss
    title: "Metalinfo — грузовая техника"
    url: "https://rss.metalinfo.ru/ru/news/s6522.html"
    tags:
      - грузовая техника
      - прицепы
      - полуприцепы

  - id: metalinfo-truck-market
    enabled: true
    kind: rss
    title: "Metalinfo — рынок грузовиков"
    url: "https://rss.metalinfo.ru/ru/news/s7170.html"
    tags:
      - рынок грузовиков
      - аналитика

  - id: motor-ru
    enabled: true
    kind: rss
    title: "Motor.ru — автоновости"
    url: "https://motor.ru/exports/rss"
    tags:
      - автоновости
      - легковые
      - общий поток

# Конфигурация каналов YouTube — пока не используется агрегатором,
# но пригодится дальше для видео-раздела
youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "ы"
    videos:
      - "jQQzPo6YWPg"
      - "AwMnAEEOfoM"
      - "_6JdduOi4CE"
      - "1ZKbQu2NQ4s"
      - "1ZKbQu2NQ4s"
      - "JArHntGs9iM"

  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "i"
    videos:
      - "Qwerty123456"
      - "Asdfgh987654"

