# Конфигурация источников для агрегатора.
# ВАЖНО: верхний уровень — это mapping с ключом `sources`.

sources:
  - id: gruzovoy-ru
    enabled: true
    kind: rss
    title: "Грузовой Ру — грузовые автомобили, прицепы, коммерческий транспорт"
    url: "https://gruzovoy.ru/rss"
    tags:
      - отрасль
      - грузовики
      - прицепы
      - коммерческий транспорт

  - id: st-kt
    enabled: true
    kind: rss
    title: "Журнал «СпецТехника и Коммерческий Транспорт»"
    url: "https://st-kt.ru/rss"
    tags:
      - отрасль
      - спецтехника
      - грузовики
      - прицепы
      - рынок

  - id: motor-ru
    enabled: true
    kind: rss
    title: "Motor.ru — автомобильные новости"
    url: "https://motor.ru/exports/rss"
    tags:
      - легковые
      - рынок
      - автоновости
      - автоспорт

  - id: gazeta-ru-autonews
    enabled: true
    kind: rss
    title: "Газета.Ru — автоновости"
    url: "https://www.gazeta.ru/export/rss/autonews.xml"
    tags:
      - рынок
      - аналитика
      - автоновости

# Видео-источники (если понадобится для блока с видео).
# Они не мешают проверке, просто лежат рядом.

youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "ы"
  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "i"

vk:
  - domain: "specavto_official"  # https://vk.com/specavto_official
    name: "СпецАвто"
