rss:
  - name: "Drom.ru (Новости)"
    url: "https://news.drom.ru/rss/"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]

  - name: "За рулём (Все новости)"
    url: "https://www.zr.ru/rss/"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]

  - name: "Motor.ru (экспорт RSS)"
    url: "https://motor.ru/export/rss.xml"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]

  - name: "Авторевю (Все)"
    url: "https://autoreview.ru/rss/all/"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]

  - name: "Автоньюс (Лента)"
    url: "https://www.autonews.ru/autonews/rss.xml"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]

  - name: "Колёса.ру (RSS)"
    url: "https://www.kolesa.ru/rss/"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]

  - name: "Грузовик-Пресс (Новости)"
    url: "https://gruzovikpress.ru/rss/"
    include_keywords: ["полуприцеп", "прицеп", "низкорам", "шторн", "рефрижератор", "самосвальн", "трал", "бортов", "контейнеровоз", "тентован", "цистерн", "седельн", "полуприцепы"]





youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "ы"
  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "i"
vk:
  - domain: "specavto_official"  # https://vk.com/specavto_official
    name: "СпецАвто"
