rss:
  # Drom.ru — новости
  - name: "Drom.ru (Новости)"
    url: "https://news.drom.ru/rss/"
    lang: "ru"
    tags: ["auto", "trucks", "trailers"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"

  # За рулём — RSS
  - name: "За рулём (Все новости)"
    url: "https://www.zr.ru/rss/"
    lang: "ru"
    tags: ["auto", "industry"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"

  # Motor.ru — общий RSS
  - name: "Motor.ru (Все)"
    url: "https://motor.ru/rss/all"
    lang: "ru"
    tags: ["auto"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"

  # Autoreview — общий RSS
  - name: "Авторевю (Все)"
    url: "https://autoreview.ru/rss/all"
    lang: "ru"
    tags: ["auto"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"

  # Autonews — RSS
  - name: "Автоньюс (Лента)"
    url: "https://www.autonews.ru/autonews/rss.xml"
    lang: "ru"
    tags: ["auto", "business"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"

  # Kolesa.ru — RSS
  - name: "Колёса.ру (RSS)"
    url: "https://www.kolesa.ru/rss/"
    lang: "ru"
    tags: ["auto"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"

  # Грузовик-Пресс — профильное издание по грузовой теме
  - name: "Грузовик-Пресс (Новости)"
    url: "https://gruzovikpress.ru/rss"
    lang: "ru"
    tags: ["trucks", "trailers", "industry"]
    include_keywords:
      - "полуприцеп"
      - "прицеп"
      - "низкорам"
      - "шторн"
      - "рефрижератор"
      - "самосвальн"
      - "трал"
      - "бортов"
      - "контейнеровоз"
      - "тентован"
      - "цистерн"
      - "седельн"
      - "полуприцепы"





youtube:
  - channel_id: "UC0SAWzOPY-BiS5NVv3vdTFw"
    name: "ы"
  - channel_id: "UCDU7Dh9zymMryM43US9bCJQ"
    name: "i"
vk:
  - domain: "specavto_official"  # https://vk.com/specavto_official
    name: "СпецАвто"
